# Generated by Django 5.1.7 on 2025-04-05 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_remove_order_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='prix',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
