POST http://127.0.0.1:8000/account/login/
Content-Type: application/json

{
  "username": "johndoe",  
  "password": "Jeanyves123456789" 
}

POST http://127.0.0.1:8000/order/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ0MjQ1Nzc1LCJpYXQiOjE3NDQyNDIxNzUsImp0aSI6ImM0OGY1OTk3NzVmNDQyYWQ4ZWRkOWEzOTU4ZjU0Y2U4IiwidXNlcl9pZCI6MX0.RYj7fAs0mRyDwzqkd3NHMOkJ5H9zWGZwRVlg1pp2fuI

{
    "items": [
        {
            "product_id": 1,
            "quantity": 2
        },
        {
            "product_id": 3,
            "quantity": 1
        }
    ]
}