### Test de la route pour obtenir toutes les catégories
GET http://127.0.0.1:8000/api/categories/ 
Accept: application/json

### Test de la route pour obtenir une catégorie spécifique
GET http://127.0.0.1:8000/api/categories/1/ 
Accept: application/json

### Test de la route pour créer une nouvelle catégorie
POST http://127.0.0.1:8000/api/categories/ 
Content-Type: application/json
{
  "nom": "Nouvelle catégorie"
}

### Test de la route pour obtenir tous les produits
GET http://127.0.0.1:8000/products/ 
Accept: application/json

### Test de la route pour obtenir un produit spécifique
GET http://127.0.0.1:8000/products/1/ 
Accept: application/json

### Test de la route pour créer un nouveau produit
POST http://127.0.0.1:8000/products/ 
Content-Type: application/json
{
  "nom": "Produit Test",
  "prix": 99.99,
  "category": 1
}

### Test de la route pour obtenir tous les produits dans une commande
GET http://127.0.0.1:8000/order-products/ 
Accept: application/json

### Test de la route pour obtenir un produit spécifique dans une commande
GET http://127.0.0.1:8000/order-products/1/ 
Accept: application/json

### Test de la route pour obtenir toutes les commandes
GET http://127.0.0.1:8000/orders/ 
Accept: application/json

### Test de la route pour obtenir une commande spécifique
GET http://127.0.0.1:8000/orders/1/ 
Accept: application/json

### Test de la route pour créer une commande
POST http://127.0.0.1:8000/order/orders/ 
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ1MTUxNjA2LCJpYXQiOjE3NDUxNDgwMDYsImp0aSI6ImQyYzQ5NzdkMzk0MjQyNDE4OWU4NWVlY2MwMmE2NjRlIiwidXNlcl9pZCI6Mn0.BKGsGq69pFAQNwJOditGqajtDIxNbjYcCOmlC6ZgxFY

{  
  "order_products": [
    {
      "product_id": 1,
      "quantity": 2
    }
  ]
}

POST http://127.0.0.1:8000/order/orders/ 
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ1MTU5MzcyLCJpYXQiOjE3NDUxNTU3NzIsImp0aSI6ImE0ZjRhMGM0NjhhNjQ1ODA5MWUyYmEzZjdjMzUzYmUxIiwidXNlcl9pZCI6Mn0.juqu7i76jhIG6V56DBWeW2PPh7Jn_mAaDuc05Qa7RMs

{
  "order_products": [
    {
    "product_name": "banane",
    "quantity": 2
    }
  ]
}

### Historique de commandes


POST http://127.0.0.1:8000/account/login/
Content-Type: application/json

{
  "username": "johndoe",
  "password": "Jeanyves123456@"
}

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ1MzMyMDk5LCJpYXQiOjE3NDUzMjg0OTksImp0aSI6ImQzZWY3ODJhMTQyYTQ3ZDg4MjgwMWY2MDJkNzNmMzI1IiwidXNlcl9pZCI6Mn0.YszZEr8cmeXRFNZ0VVKHkWJTw3d7MB_rw9XUO-fI7BE
@refresh = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc0NTkzMzI5OSwiaWF0IjoxNzQ1MzI4NDk5LCJqdGkiOiIwZTJhYzNhMTA0YTk0ZDE0OTJiMDg4ZTU1MThhYzM1MyIsInVzZXJfaWQiOjJ9.ZS3pNaYqPNQiaeRPsZEIYOX1IgdXPukjLeUoFSUmT-I


GET http://127.0.0.1:8000/order/history/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ1MzMyMDk5LCJpYXQiOjE3NDUzMjg0OTksImp0aSI6ImQzZWY3ODJhMTQyYTQ3ZDg4MjgwMWY2MDJkNzNmMzI1IiwidXNlcl9pZCI6Mn0.YszZEr8cmeXRFNZ0VVKHkWJTw3d7MB_rw9XUO-fI7BE